version: "3.7"
services:
  atms_backend:
    build: ./backend
    container_name: atms_backend
    ports:
      - '1337:1337'
    env_file: ./backend/.env

  atms_frontend:
    build: ./frontend
    container_name: atms_frontend
    ports:
      - '3000:3000'
    env_file: ./frontend/.env
  
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin


     